---
- name: installing and launching filebeat
  hosts: webservers
  become: yes
  tasks:

  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.7.0-amd64.deb

  - name: install metricbeat deb
    command: dpkg -i metricbeat-7.7.0-amd64.deb

  - name: drop in metricbeat.yml
    copy:
      src: files/metricbeat-configuration.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure docker module
    command: metricbeat modules enable docker

  - name: setup metricbeat
    command: metricbeat setup

  - name: start metricbeat service
    command: service metricbeat start

  - name: make metricbeat persistent
    command: systemctl enable metricbeat
